---
- name: Deploy Application with Docker
  hosts: dev
  user: ansible
  become: yes
  connection: ssh
  gather_facts: no
  tasks:

    - name: Remove old Docker container if exists
      command: docker rm -f web
      ignore_errors: yes

    - name: Remove old Docker image if exists
      command: docker rmi -f sanjana255/alb-terra:latest
      ignore_errors: yes

    - name: Log in to Docker Hub
      command: echo "Biradar@24" | docker login -u sanjana255 --password-stdin

    - name: Pull Docker Image from Docker Hub
      command: docker pull sanjana255/alb-terra:latest

    - name: Run Docker Container
      command: docker run -it -d --name web -p 8081:8080 sanjana255/alb-terra:latest